version: '3.8'

services:
  app:
    container_name: gamabuild-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: always
    env_file:
      - .env
    network_mode: "host"
    
  redis:
    container_name: redis-gamabuild
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: always