version: '3.8'

services:
  app:
    container_name: gamabuild-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: always
    env_file:
      - .env
    networks:
      - gama-network
    
  redis:
    container_name: redis-gamabuild
    image: "redis:latest"
    restart: always
    networks:
      - gama-network

networks:
  gama-network:
    driver: bridge
