name: Docker Build and Deployment

on: workflow_dispatch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_TOKEN }}
        image_name: zebco/gamabuild-app


  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    
    steps:
    
    - name: SSH to server and run Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker rm -f gamabuild-app || true
          docker pull zebco/gamabuild-app:latest
          docker run -d --name gamabuild-app --restart always --network host -e TOKEN=${{ secrets.GAMABUILD_TOKEN }} zebco/gamabuild-app:latest
